name: Release Compliance

on:
  release:
    types: [published]

jobs:
  compliance:
    name: Automated Release Compliance Governor
    runs-on: ubuntu-latest
    permissions:
      contents: read   # read release and repository context

    steps:
      - name: Automated Release Compliance Governor
        uses: etailory/automated-release-compliance-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
